/**
 * Catalogue des corps célestes — SOURCE UNIQUE.
 *
 * Chaque entrée porte tout ce qui définit un corps : taille, rotation, couleur d'orbite,
 * anneaux, satellites, données astronomiques réelles (`realData`), enum astronomy-engine
 * (`astroBody`), référentiel (`frame`), distance de visite caméra (`cameraDistance`) et
 * rang de préchargement (`loadPriority`).
 *
 * Ajouter un corps = une entrée ici + son dossier de textures. Tout le reste (boutons de
 * navigation, préchargement, éphéméride, hiérarchie de scène) se dérive du catalogue.
 */
import { Body } from 'astronomy-engine';
import type { CelestialConfig } from '@/types';
import { exploCameraDistance } from '@/core/ScaleService';
import { DEG_TO_RAD as D2R } from '@/core/MathConstants';
import {
  assertUniqueBodyNames,
  deriveTextures,
  forEachBody,
  ringTexturePath,
} from './catalog';
import { assertValidCelestialCatalog } from './catalogValidation';
import { SMALL_BODIES } from './smallBodies';

// Vitesse de rotation axiale — rad / seconde de simulation.
const _R = (hours: number): number => (Math.PI * 2) / (hours * 3_600);

export const CELESTIAL_CONFIG: CelestialConfig = {
  bodies: {
    stars: {
      kind: 'skybox',
      radius: 0,
      rotationSpeed: 0,
      orbitalColor: 0x000000,
      textureResolutions: { surface: ['8k', '4k', '2k', '1k'] },
      loadPriority: 0,
    },

    sun: {
      kind: 'star',
      displayName: { fr: 'Soleil' },
      // Rayon éducatif volontairement tempéré : le Soleil reste dominant sans saturer la vue.
      // En Explo, le rayon physique de realData.radiusKm reprend entièrement la main.
      radius: 7,
      rotationSpeed: _R(609.6),
      orbitalColor: 0x000000,
      textureResolutions: { surface: ['4k', '2k', '1k'] },
      realData: {
        radiusKm: 695_700,
        axialTilt: 7.25 * D2R,
        massKg: 1.989e30,
        gravity: 274,
        meanTempC: 5505,
        moonCount: 8,
        description: {
          en: 'The star at the heart of the Solar System. This ball of plasma holds 99.86% of all the mass orbiting it.',
          fr: 'L’étoile au cœur du Système solaire. Cette boule de plasma concentre 99,86 % de toute la masse en orbite autour d’elle.',
        },
        wiki: {
          en: 'https://en.wikipedia.org/wiki/Sun',
          fr: 'https://fr.wikipedia.org/wiki/Soleil',
        },
      },
      astroBody: Body.Sun,
      cameraDistance: { educ: 50, explo: exploCameraDistance(695_700) },
      loadPriority: 1,
    },

    mercury: {
      kind: 'planet',
      displayName: { fr: 'Mercure' },
      radius: 0.38,
      rotationSpeed: _R(1407.6),
      orbitalColor: 0xb8b0a5,
      textureResolutions: { surface: ['8k', '4k', '2k', '1k'] },
      realData: {
        radiusKm: 2_440,
        distanceAU: 0.387,
        orbitPeriodDays: 87.97,
        orbitalInclination: 7.005 * D2R,
        ascendingNode: 48.331 * D2R,
        axialTilt: 0.034 * D2R,
        massKg: 3.301e23,
        gravity: 3.7,
        meanTempC: 167,
        moonCount: 0,
        description: {
          en: 'The smallest planet and the closest to the Sun. With no atmosphere, it swings from +430 °C by day to -180 °C at night.',
          fr: 'La plus petite planète et la plus proche du Soleil. Sans atmosphère, elle passe de +430 °C le jour à -180 °C la nuit.',
        },
        wiki: {
          en: 'https://en.wikipedia.org/wiki/Mercury_(planet)',
          fr: 'https://fr.wikipedia.org/wiki/Mercure_(plan%C3%A8te)',
        },
      },
      astroBody: Body.Mercury,
      cameraDistance: { educ: 2, explo: exploCameraDistance(2_440) },
      loadPriority: 8,
    },

    venus: {
      kind: 'planet',
      displayName: { fr: 'Vénus' },
      radius: 0.95,
      rotationSpeed: _R(5832.6),
      orbitalColor: 0xe9a13b,
      textureResolutions: {
        surface: ['8k', '4k', '2k', '1k'],
        // Le voile nuageux opaque de Vénus est rendu comme couche `clouds`
        // (sphère texturée), le halo atmosphérique Fresnel s'ajoutant au limbe.
        clouds: ['4k', '2k', '1k'],
      },
      atmosphereColor: 0xd9b26a,
      realData: {
        radiusKm: 6_052,
        distanceAU: 0.723,
        orbitPeriodDays: 224.7,
        orbitalInclination: 3.395 * D2R,
        ascendingNode: 76.68 * D2R,
        axialTilt: 177.36 * D2R,
        massKg: 4.867e24,
        gravity: 8.87,
        meanTempC: 464,
        moonCount: 0,
        description: {
          en: 'The hottest planet. Its thick CO₂ atmosphere traps heat through a runaway greenhouse effect, and it spins backwards, very slowly.',
          fr: 'La planète la plus chaude. Son épaisse atmosphère de CO₂ piège la chaleur par un effet de serre emballé, et elle tourne à l’envers, très lentement.',
        },
        wiki: {
          en: 'https://en.wikipedia.org/wiki/Venus',
          fr: 'https://fr.wikipedia.org/wiki/V%C3%A9nus_(plan%C3%A8te)',
        },
      },
      astroBody: Body.Venus,
      cameraDistance: { educ: 5, explo: exploCameraDistance(6_052) },
      loadPriority: 7,
    },

    earth: {
      kind: 'planet',
      displayName: { fr: 'Terre' },
      radius: 1,
      rotationSpeed: _R(23.9345),
      orbitalColor: 0x2f9dff,
      textureResolutions: {
        surface: ['8k', '4k', '2k', '1k'],
        normalMap: ['8k', '4k', '2k', '1k'],
        displacement: ['2k', '1k'],
        clouds: ['8k', '4k', '2k', '1k'],
        spec: ['8k', '4k', '2k', '1k'],
        lights: ['8k', '4k', '2k', '1k'],
      },
      // L'atmosphère terrestre est un phénomène de diffusion rendu par shader ; elle
      // ne nécessite pas une texture bitmap supplémentaire.
      atmosphereColor: 0x4a90e0,
      realData: {
        radiusKm: 6_371,
        distanceAU: 1.0,
        orbitPeriodDays: 365.25,
        orbitalInclination: 0,
        ascendingNode: 0,
        axialTilt: 23.44 * D2R,
        massKg: 5.972e24,
        gravity: 9.81,
        meanTempC: 15,
        moonCount: 1,
        description: {
          en: 'The only known planet to harbour life. Liquid water covers 71% of its surface, and its atmosphere shields it from solar radiation.',
          fr: 'La seule planète connue à abriter la vie. L’eau liquide couvre 71 % de sa surface, et son atmosphère la protège du rayonnement solaire.',
        },
        wiki: {
          en: 'https://en.wikipedia.org/wiki/Earth',
          fr: 'https://fr.wikipedia.org/wiki/Terre',
        },
      },
      astroBody: Body.Earth,
      // Position au barycentre Terre-Lune : évite le ballant lunaire réel (~4700 km, ~27 j)
      // qui se voit comme un zigzag à vraie échelle et vitesse max. L'axe/jour-nuit reste sur
      // Body.Earth. La Lune (parentRelative) est alors référencée à l'EMB, restant à sa vraie position.
      positionBody: Body.EMB,
      cameraDistance: { educ: 5, explo: exploCameraDistance(6_371) },
      loadPriority: 2,
      satellites: {
        moon: {
          kind: 'moon',
          displayName: { fr: 'Lune' },
          frame: 'parentRelative',
          radius: 0.27,
          rotationSpeed: _R(655.72),
          orbitalColor: 0x8f98a5,
          textureResolutions: {
            surface: ['8k', '4k', '2k', '1k'],
          },
          realData: {
            radiusKm: 1_737,
            distanceAU: 0.00257,
            orbitPeriodDays: 27.32,
            orbitalInclination: 5.145 * D2R,
            ascendingNode: 0,
            axialTilt: 6.68 * D2R,
            massKg: 7.342e22,
            gravity: 1.62,
            meanTempC: -20,
            moonCount: 0,
            description: {
              en: "Earth's only natural satellite. It always shows the same face and stabilises our planet's axial tilt.",
              fr: 'Le seul satellite naturel de la Terre. Elle montre toujours la même face et stabilise l’inclinaison de l’axe de notre planète.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Moon',
              fr: 'https://fr.wikipedia.org/wiki/Lune',
            },
          },
          astroBody: Body.Moon,
          cameraDistance: { educ: 2, explo: exploCameraDistance(1_737) },
          loadPriority: 3,
        },
      },
    },

    mars: {
      kind: 'planet',
      radius: 0.53,
      rotationSpeed: _R(24.6229),
      orbitalColor: 0xe85d3f,
      textureResolutions: {
        surface: ['8k', '4k', '2k', '1k'],
      },
      realData: {
        radiusKm: 3_390,
        distanceAU: 1.524,
        orbitPeriodDays: 686.97,
        orbitalInclination: 1.85 * D2R,
        ascendingNode: 49.579 * D2R,
        axialTilt: 25.19 * D2R,
        massKg: 6.417e23,
        gravity: 3.71,
        meanTempC: -63,
        moonCount: 2,
        description: {
          en: 'The red planet, tinted by iron oxide. It hosts Olympus Mons, the tallest volcano in the Solar System (~22 km).',
          fr: 'La planète rouge, teintée par l’oxyde de fer. Elle abrite Olympus Mons, le plus haut volcan du Système solaire (~22 km).',
        },
        wiki: {
          en: 'https://en.wikipedia.org/wiki/Mars',
          fr: 'https://fr.wikipedia.org/wiki/Mars_(plan%C3%A8te)',
        },
      },
      astroBody: Body.Mars,
      cameraDistance: { educ: 3, explo: exploCameraDistance(3_390) },
      loadPriority: 4,
      satellites: {
        phobos: {
          kind: 'moon',
          displayName: { en: 'Phobos', fr: 'Phobos' },
          radius: 0.08,
          rotationSpeed: _R(7.6488),
          orbitalColor: 0xb6a28d,
          fallbackColor: 0x8f7b69,
          frame: 'parentRelative',
          rotationBody: Body.Mars,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.0000626680043,
            eccentricity: 0.015,
            inclinationRad: 1.1 * D2R,
            ascendingNodeRad: 169.2 * D2R,
            argPerihelionRad: 216.3 * D2R,
            meanAnomalyAtEpochRad: 189.7 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: { surface: ['8k', '4k', '2k', '1k'] },
          realData: {
            radiusKm: 11.08,
            distanceAU: 0.0000626680043,
            orbitPeriodDays: 0.3187,
            orbitalInclination: 1.1 * D2R,
            ascendingNode: 169.2 * D2R,
            axialTilt: 0,
            massKg: 1.0659e16,
            gravity: 0.0057,
            meanTempC: -40,
            moonCount: 0,
            description: {
              en: "The larger and faster-orbiting of Mars' two small moons, shaped by ancient impacts.",
              fr: 'La plus grande et la plus rapide des deux petites lunes de Mars, façonnée par les impacts anciens.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Phobos_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Phobos_(lune)',
            },
          },
          cameraDistance: { educ: 0.35, explo: exploCameraDistance(11.08) },
          loadPriority: 11,
        },
        deimos: {
          kind: 'moon',
          displayName: { en: 'Deimos', fr: 'Déimos' },
          radius: 0.06,
          rotationSpeed: _R(30.3),
          orbitalColor: 0xc1aa91,
          fallbackColor: 0x927d68,
          frame: 'parentRelative',
          rotationBody: Body.Mars,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.00015680036,
            eccentricity: 0,
            inclinationRad: 1.8 * D2R,
            ascendingNodeRad: 54.3 * D2R,
            argPerihelionRad: 0,
            meanAnomalyAtEpochRad: 205 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: { surface: ['1k'] },
          realData: {
            radiusKm: 6.2,
            distanceAU: 0.00015680036,
            orbitPeriodDays: 1.2625,
            orbitalInclination: 1.8 * D2R,
            ascendingNode: 54.3 * D2R,
            axialTilt: 0.9 * D2R,
            massKg: 1.4762e15,
            gravity: 0.003,
            meanTempC: -40,
            moonCount: 0,
            description: {
              en: "Mars' smaller outer moon, a dark irregular body with a slow synchronous orbit.",
              fr: 'La plus petite lune extérieure de Mars, un corps sombre et irrégulier en orbite synchrone lente.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Deimos_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/D%C3%A9imos_(lune)',
            },
          },
          cameraDistance: { educ: 0.3, explo: exploCameraDistance(6.2) },
          loadPriority: 11,
        },
      },
    },

    jupiter: {
      kind: 'planet',
      radius: 4,
      rotationSpeed: _R(9.9259),
      orbitalColor: 0xd89a5b,
      textureResolutions: { surface: ['4k', '2k', '1k'] },
      realData: {
        radiusKm: 71_492,
        distanceAU: 5.203,
        orbitPeriodDays: 4332.59,
        orbitalInclination: 1.304 * D2R,
        ascendingNode: 100.464 * D2R,
        axialTilt: 3.13 * D2R,
        massKg: 1.898e27,
        gravity: 24.79,
        meanTempC: -108,
        // Compte de lunes confirmées : chiffre datant, mis à jour vers la valeur courante
        // (source JPL via l'infobox Wikipedia, 2026) — les lots de nouvelles lunes confirmées
        // par l'UAI rendent ce chiffre daté en quelques années, pas figé une fois pour toutes.
        moonCount: 115,
        description: {
          en: 'The giant of the Solar System, more massive than all the other planets combined. Its Great Red Spot is a storm centuries old.',
          fr: 'La géante du Système solaire, plus massive que toutes les autres planètes réunies. Sa Grande Tache rouge est une tempête vieille de plusieurs siècles.',
        },
        wiki: {
          en: 'https://en.wikipedia.org/wiki/Jupiter',
          fr: 'https://fr.wikipedia.org/wiki/Jupiter_(plan%C3%A8te)',
        },
      },
      astroBody: Body.Jupiter,
      cameraDistance: { educ: 25, explo: exploCameraDistance(71_492) },
      loadPriority: 5,
      satellites: {
        amalthea: {
          kind: 'moon',
          displayName: { en: 'Amalthea', fr: 'Amalthée' },
          frame: 'parentRelative',
          rotationBody: Body.Jupiter,
          radius: 0.06,
          rotationSpeed: _R(0.5016447757055735 * 24),
          orbitalColor: 0xa8544a,
          fallbackColor: 0x9c4a3c,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          // JPL Horizons osculating elements, epoch 2000-01-01.5 TDB (EPHEM_TYPE=ELEMENTS,
          // TLIST=2451545.0) — même méthode que les autres lunes de ce fichier. Vérifiée
          // cohérente avec la période réelle publiée (0.498 j).
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.0012165730245027,
            eccentricity: 0.006131496682479541,
            inclinationRad: 2.442089133637652 * D2R,
            ascendingNodeRad: 330.4106584847095 * D2R,
            argPerihelionRad: 105.1175845531084 * D2R,
            meanAnomalyAtEpochRad: 336.2664083066824 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          // Aucune mosaïque photo globale contrôlée n'existe côté USGS pour Amalthea (imagée
          // partiellement par Galileo, jamais assemblée en carte globale contrôlée) — vérifié
          // en direct (2026-08-26). Sphère de couleur unie plutôt qu'une texture inventée.
          textureResolutions: {},
          realData: {
            radiusKm: 83.5,
            distanceAU: 0.0012165730245027,
            orbitPeriodDays: 0.5016447757055735,
            orbitalInclination: 2.442089133637652 * D2R,
            ascendingNode: 330.4106584847095 * D2R,
            axialTilt: 0,
            massKg: 2.4655e18,
            gravity: 0.0236,
            meanTempC: -108,
            moonCount: 0,
            description: {
              en: "Jupiter's reddest moon, tidally locked with its long axis always pointing at the planet, likely stained by sulfur from Io.",
              fr: 'La lune la plus rouge de Jupiter, verrouillée par effet de marée avec son grand axe toujours pointé vers la planète, probablement teintée par le soufre en provenance d’Io.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Amalthea_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Amalth%C3%A9e_(lune)',
            },
          },
          cameraDistance: { educ: 0.5, explo: exploCameraDistance(83.5) },
          loadPriority: 10,
        },
        io: {
          kind: 'moon',
          displayName: { fr: 'Io' },
          frame: 'parentRelative',
          relativeEphemeris: { kind: 'jupiterMoon', moon: 'io' },
          rotationBody: Body.Jupiter,
          radius: 0.13,
          rotationSpeed: _R(42.46),
          orbitalColor: 0xffc857,
          fallbackColor: 0xffc857,
          textureResolutions: { surface: ['8k', '4k', '2k', '1k'] },
          realData: {
            radiusKm: 1_821.6,
            distanceAU: 0.002819,
            orbitPeriodDays: 1.769,
            orbitalInclination: 0,
            ascendingNode: 0,
            axialTilt: 0,
            moonCount: 0,
            description: {
              en: 'The innermost Galilean moon, shaped by intense volcanic activity driven by Jupiter tides.',
              fr: 'La plus proche des lunes galiléennes, modelée par une activité volcanique intense entretenue par les marées de Jupiter.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Io_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Io_(lune)',
            },
          },
          cameraDistance: { educ: 1.2, explo: exploCameraDistance(1_821.6) },
          loadPriority: 11,
        },
        europa: {
          kind: 'moon',
          displayName: { fr: 'Europe' },
          frame: 'parentRelative',
          relativeEphemeris: { kind: 'jupiterMoon', moon: 'europa' },
          rotationBody: Body.Jupiter,
          radius: 0.12,
          rotationSpeed: _R(85.22),
          orbitalColor: 0xd9c7a4,
          fallbackColor: 0xd9c7a4,
          textureResolutions: { surface: ['8k', '4k', '2k', '1k'] },
          realData: {
            radiusKm: 1_560.8,
            distanceAU: 0.004486,
            orbitPeriodDays: 3.551,
            orbitalInclination: 0,
            ascendingNode: 0,
            axialTilt: 0,
            moonCount: 0,
            description: {
              en: 'An icy moon with a smooth surface and strong evidence for a global subsurface ocean.',
              fr: 'Une lune glacée à la surface lisse, avec de fortes preuves de l’existence d’un océan souterrain global.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Europa_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Europe_(lune)',
            },
          },
          cameraDistance: { educ: 1.2, explo: exploCameraDistance(1_560.8) },
          loadPriority: 12,
        },
        ganymede: {
          kind: 'moon',
          displayName: { fr: 'Ganymède' },
          frame: 'parentRelative',
          relativeEphemeris: { kind: 'jupiterMoon', moon: 'ganymede' },
          rotationBody: Body.Jupiter,
          radius: 0.2,
          rotationSpeed: _R(171.7),
          orbitalColor: 0x9c8b78,
          fallbackColor: 0x9c8b78,
          textureResolutions: { surface: ['8k', '4k', '2k', '1k'] },
          realData: {
            radiusKm: 2_631.2,
            distanceAU: 0.007155,
            orbitPeriodDays: 7.155,
            orbitalInclination: 0,
            ascendingNode: 0,
            axialTilt: 0,
            moonCount: 0,
            description: {
              en: 'The largest moon in the Solar System, larger than Mercury, with its own intrinsic magnetic field.',
              fr: 'La plus grande lune du Système solaire, plus grande que Mercure, et dotée de son propre champ magnétique.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Ganymede_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Ganym%C3%A8de_(lune)',
            },
          },
          cameraDistance: { educ: 1.5, explo: exploCameraDistance(2_634.1) },
          loadPriority: 13,
        },
        callisto: {
          kind: 'moon',
          displayName: { fr: 'Callisto' },
          frame: 'parentRelative',
          relativeEphemeris: { kind: 'jupiterMoon', moon: 'callisto' },
          rotationBody: Body.Jupiter,
          radius: 0.18,
          rotationSpeed: _R(400.5),
          orbitalColor: 0x7c746f,
          fallbackColor: 0x7c746f,
          textureResolutions: { surface: ['8k', '4k', '2k', '1k'] },
          realData: {
            radiusKm: 2_410.3,
            distanceAU: 0.012585,
            orbitPeriodDays: 16.689,
            orbitalInclination: 0,
            ascendingNode: 0,
            axialTilt: 0,
            moonCount: 0,
            description: {
              en: 'The outermost Galilean moon, heavily cratered and likely hiding a deep salty ocean.',
              fr: 'La plus éloignée des lunes galiléennes, fortement cratérisée et susceptible d’abriter un océan salé profond.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Callisto_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Callisto_(moon)',
            },
          },
          cameraDistance: { educ: 1.5, explo: exploCameraDistance(2_410.3) },
          loadPriority: 14,
        },
      },
    },

    saturn: {
      kind: 'planet',
      displayName: { fr: 'Saturne' },
      radius: 3.5,
      rotationSpeed: _R(10.656),
      orbitalColor: 0xe7d28d,
      ring: {
        bodyName: 'saturn-ring',
        innerRadius: 1.5,
        outerRadius: 2.2,
        textureResolutions: ['8k', '4k', '2k', '1k'],
      },
      textureResolutions: { surface: ['4k', '2k', '1k'] },
      realData: {
        radiusKm: 60_268,
        distanceAU: 9.537,
        orbitPeriodDays: 10759.22,
        orbitalInclination: 2.485 * D2R,
        ascendingNode: 113.665 * D2R,
        axialTilt: 26.73 * D2R,
        massKg: 5.683e26,
        gravity: 10.44,
        meanTempC: -139,
        // Voir le commentaire équivalent sur Jupiter : chiffre daté, mis à jour (source JPL
        // via l'infobox Wikipedia, 2026) — un gros lot de lunes irrégulières confirmées par
        // l'UAI en 2023 a fait plus que doubler ce chiffre en quelques années.
        moonCount: 293,
        description: {
          en: 'Famous for its spectacular rings, made of billions of chunks of ice and rock. So low in density it would float on water.',
          fr: 'Célèbre pour ses anneaux spectaculaires, faits de milliards de blocs de glace et de roche. Si peu dense qu’elle flotterait sur l’eau.',
        },
        wiki: {
          en: 'https://en.wikipedia.org/wiki/Saturn',
          fr: 'https://fr.wikipedia.org/wiki/Saturne_(plan%C3%A8te)',
        },
      },
      astroBody: Body.Saturn,
      cameraDistance: { educ: 20, explo: exploCameraDistance(60_268) },
      loadPriority: 6,
      satellites: {
        enceladus: {
          kind: 'moon',
          displayName: { en: 'Enceladus', fr: 'Encelade' },
          radius: 0.12,
          rotationSpeed: _R(32.885232),
          orbitalColor: 0xdedbd4,
          fallbackColor: 0xc7c8c9,
          frame: 'parentRelative',
          rotationBody: Body.Saturn,
          // JPL SAT441 mean elements, epoch 2000-01-01.5 TDB.
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.00159360557,
            eccentricity: 0.005,
            inclinationRad: 0,
            ascendingNodeRad: 0,
            argPerihelionRad: 119.5 * D2R,
            meanAnomalyAtEpochRad: 57 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: { surface: ['1k'] },
          realData: {
            radiusKm: 252.1,
            distanceAU: 0.00159360557,
            orbitPeriodDays: 1.370218,
            orbitalInclination: 0,
            ascendingNode: 0,
            axialTilt: 0,
            massKg: 1.08022e20,
            gravity: 0.113,
            meanTempC: -201,
            moonCount: 0,
            description: {
              en: 'A bright icy moon with an active south-polar plume and a subsurface ocean.',
              fr: 'Une lune glacée très brillante, avec un panache actif au pôle sud et un océan souterrain.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Enceladus',
              fr: 'https://fr.wikipedia.org/wiki/Encelade_(lune)',
            },
          },
          cameraDistance: { educ: 0.8, explo: exploCameraDistance(252.1) },
          loadPriority: 8,
        },
        rhea: {
          kind: 'moon',
          displayName: { en: 'Rhea', fr: 'Rhéa' },
          radius: 0.2,
          rotationSpeed: _R(108.420072),
          orbitalColor: 0xbcb9b1,
          fallbackColor: 0xa4a39e,
          frame: 'parentRelative',
          rotationBody: Body.Saturn,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          // JPL SAT441 mean elements, epoch 2000-01-01.5 TDB.
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.00352411433,
            eccentricity: 0.001,
            inclinationRad: 0.3 * D2R,
            ascendingNodeRad: 133.7 * D2R,
            argPerihelionRad: 44.3 * D2R,
            meanAnomalyAtEpochRad: 31.5 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: { surface: ['1k'] },
          realData: {
            radiusKm: 763.5,
            distanceAU: 0.00352411433,
            orbitPeriodDays: 4.517503,
            orbitalInclination: 0.3 * D2R,
            ascendingNode: 133.7 * D2R,
            axialTilt: 0,
            massKg: 2.3065e21,
            gravity: 0.264,
            meanTempC: -174,
            moonCount: 0,
            description: {
              en: "Saturn's second-largest moon, a heavily cratered world of bright water ice.",
              fr: "La deuxième plus grande lune de Saturne, un monde de glace d'eau très cratérisé.",
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Rhea_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Rh%C3%A9a_(lune)',
            },
          },
          cameraDistance: { educ: 1, explo: exploCameraDistance(763.5) },
          loadPriority: 8,
        },
        iapetus: {
          kind: 'moon',
          displayName: { en: 'Iapetus', fr: 'Japet' },
          radius: 0.18,
          rotationSpeed: _R(1903.944048),
          orbitalColor: 0x9b8d79,
          fallbackColor: 0x756e62,
          frame: 'parentRelative',
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          rotationBody: Body.Saturn,
          // JPL SAT441 mean elements, epoch 2000-01-01.5 TDB.
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.02380849395,
            eccentricity: 0.028,
            inclinationRad: 7.6 * D2R,
            ascendingNodeRad: 86.5 * D2R,
            argPerihelionRad: 254.5 * D2R,
            meanAnomalyAtEpochRad: 74.8 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: { surface: ['4k', '2k', '1k'] },
          realData: {
            radiusKm: 734.3,
            distanceAU: 0.02380849395,
            orbitPeriodDays: 79.331002,
            orbitalInclination: 7.6 * D2R,
            ascendingNode: 86.5 * D2R,
            axialTilt: 0,
            massKg: 1.805e21,
            gravity: 0.223,
            meanTempC: -143,
            moonCount: 0,
            description: {
              en: 'A two-toned outer moon known for its dark leading hemisphere and equatorial ridge.',
              fr: 'Une lune extérieure bicolore, connue pour son hémisphère avant sombre et sa crête équatoriale.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Iapetus_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Japet_(lune)',
            },
          },
          cameraDistance: { educ: 1.2, explo: exploCameraDistance(734.3) },
          loadPriority: 8,
        },
        titan: {
          kind: 'moon',
          displayName: { en: 'Titan', fr: 'Titan' },
          radius: 0.55,
          rotationSpeed: _R(382.690752),
          orbitalColor: 0xc78b57,
          fallbackColor: 0x9b6a45,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          frame: 'parentRelative',
          rotationBody: Body.Saturn,
          // JPL SAT441 mean elements, epoch 2000-01-01.5 TDB.
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.008167897,
            eccentricity: 0.029,
            inclinationRad: 0.3 * D2R,
            ascendingNodeRad: 78.6 * D2R,
            argPerihelionRad: 78.3 * D2R,
            meanAnomalyAtEpochRad: 11.7 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: { surface: ['2k', '1k'] },
          realData: {
            radiusKm: 2_574.76,
            distanceAU: 0.008167897,
            orbitPeriodDays: 15.945448,
            orbitalInclination: 0.3 * D2R,
            ascendingNode: 78.6 * D2R,
            axialTilt: 26.7 * D2R,
            massKg: 1.3452e23,
            gravity: 1.352,
            meanTempC: -179,
            moonCount: 0,
            description: {
              en: "Saturn's largest moon, with a dense atmosphere and rivers, lakes, and seas of methane and ethane.",
              fr: "La plus grande lune de Saturne, avec une atmosphere dense et des rivieres, lacs et mers de methane et d'ethane.",
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Titan_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Titan_(lune)',
            },
          },
          cameraDistance: { educ: 2.5, explo: exploCameraDistance(2_574.76) },
          loadPriority: 7,
        },
        mimas: {
          kind: 'moon',
          displayName: { en: 'Mimas', fr: 'Mimas' },
          radius: 0.09,
          rotationSpeed: _R(0.9474714974314932 * 24),
          orbitalColor: 0xd9d6cd,
          fallbackColor: 0xcac8c2,
          frame: 'parentRelative',
          rotationBody: Body.Saturn,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          // JPL Horizons osculating elements, epoch 2000-01-01.5 TDB (EPHEM_TYPE=ELEMENTS,
          // TLIST=2451545.0) — même méthode que pour les autres lunes de ce fichier.
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.001243579347218559,
            eccentricity: 0.02175635,
            inclinationRad: 27.00265761372071 * D2R,
            ascendingNodeRad: 172.0569449519339 * D2R,
            argPerihelionRad: 108.7253838060412 * D2R,
            meanAnomalyAtEpochRad: 37.39805775106126 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          // Aucune mosaïque photo globale contrôlée n'existe côté USGS pour Mimas (seulement
          // relief ombré et carte picturale, pas une texture réelle) — vérifié en direct
          // (2026-08-26, voir scripts/texture-sources.json). Sphère de couleur unie plutôt
          // qu'une texture inventée.
          textureResolutions: {},
          realData: {
            radiusKm: 198.2,
            distanceAU: 0.001243579347218559,
            orbitPeriodDays: 0.9474714974314932,
            orbitalInclination: 27.00265761372071 * D2R,
            ascendingNode: 172.0569449519339 * D2R,
            axialTilt: 0,
            massKg: 3.75e19,
            gravity: 0.0637,
            meanTempC: -200,
            moonCount: 0,
            description: {
              en: "Saturn's closest major moon, dominated by the giant Herschel crater that gives it a Death-Star silhouette.",
              fr: 'La lune majeure la plus proche de Saturne, dominée par le cratère géant Herschel qui lui donne une silhouette d’Étoile Noire.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Mimas_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Mimas_(lune)',
            },
          },
          cameraDistance: { educ: 0.6, explo: exploCameraDistance(198.2) },
          loadPriority: 20,
        },
        tethys: {
          kind: 'moon',
          displayName: { en: 'Tethys', fr: 'Téthys' },
          radius: 0.16,
          rotationSpeed: _R(1.891720538046730 * 24),
          orbitalColor: 0xe3e0d6,
          fallbackColor: 0xd8d5cc,
          frame: 'parentRelative',
          rotationBody: Body.Saturn,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.001971821201097222,
            eccentricity: 0.00096988,
            inclinationRad: 27.22072909012297 * D2R,
            ascendingNodeRad: 167.9977256763769 * D2R,
            argPerihelionRad: 158.0570744864902 * D2R,
            meanAnomalyAtEpochRad: 350.3828192477454 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: { surface: ['1k'] },
          realData: {
            radiusKm: 531.1,
            distanceAU: 0.001971821201097222,
            orbitPeriodDays: 1.891720538046730,
            orbitalInclination: 27.22072909012297 * D2R,
            ascendingNode: 167.9977256763769 * D2R,
            axialTilt: 0,
            massKg: 6.175e20,
            gravity: 0.1462,
            meanTempC: -187,
            moonCount: 0,
            description: {
              en: 'An icy moon almost as bright as fresh snow, scarred by the vast Ithaca Chasma canyon and the Odysseus impact basin.',
              fr: 'Une lune glacée presque aussi brillante que de la neige fraîche, marquée par le vaste canyon Ithaca Chasma et le bassin d’impact Odysseus.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Tethys_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/T%C3%A9thys_(lune)',
            },
          },
          cameraDistance: { educ: 1, explo: exploCameraDistance(531.1) },
          loadPriority: 21,
        },
        dione: {
          kind: 'moon',
          displayName: { en: 'Dione', fr: 'Dioné' },
          radius: 0.17,
          rotationSpeed: _R(2.740345816432255 * 24),
          orbitalColor: 0xcac7bd,
          fallbackColor: 0xc9c7bf,
          frame: 'parentRelative',
          rotationBody: Body.Saturn,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.002524448888976435,
            eccentricity: 0.00292836,
            inclinationRad: 28.04139510566285 * D2R,
            ascendingNodeRad: 169.4701967860710 * D2R,
            argPerihelionRad: 164.9353995421455 * D2R,
            meanAnomalyAtEpochRad: 332.0565629313631 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: { surface: ['1k'] },
          realData: {
            radiusKm: 561.4,
            distanceAU: 0.002524448888976435,
            orbitPeriodDays: 2.740345816432255,
            orbitalInclination: 28.04139510566285 * D2R,
            ascendingNode: 169.4701967860710 * D2R,
            axialTilt: 0,
            massKg: 1.0955e21,
            gravity: 0.232,
            meanTempC: -186,
            moonCount: 0,
            description: {
              en: 'A dense icy moon with bright wispy fractures cutting across its darker, cratered trailing hemisphere.',
              fr: 'Une lune glacée dense, striée de fractures brillantes qui traversent son hémisphère arrière plus sombre et cratérisé.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Dione_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Dion%C3%A9_(lune)',
            },
          },
          cameraDistance: { educ: 1, explo: exploCameraDistance(561.4) },
          loadPriority: 22,
        },
        hyperion: {
          kind: 'moon',
          displayName: { en: 'Hyperion', fr: 'Hypérion' },
          radius: 0.08,
          // Rotation CHAOTIQUE, pas synchrone (résonance orbitale 4:3 avec Titan + forme
          // très irrégulière) — contrairement à toutes les autres lunes de ce fichier, il n'y
          // a pas de "vraie" période de rotation fixe. Valeur approximative (période moyenne
          // observée), documentée comme telle plutôt que présentée comme une synchronisation
          // réelle.
          rotationSpeed: _R(13 * 24),
          orbitalColor: 0xa08670,
          fallbackColor: 0x8a7060,
          frame: 'parentRelative',
          rotationBody: Body.Saturn,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.009927017407098830,
            eccentricity: 0.126731,
            inclinationRad: 27.20902903280515 * D2R,
            ascendingNodeRad: 168.3050139917620 * D2R,
            argPerihelionRad: 188.6932689050722 * D2R,
            meanAnomalyAtEpochRad: 70.60386395985986 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          // Aucune mosaïque globale : Hyperion est trop irrégulier (éponge poreuse
          // ~180×133×103 km) pour qu'une "carte globale" ait vraiment un sens — vérifié en
          // direct (2026-08-26, voir texture-sources.json).
          textureResolutions: {},
          realData: {
            radiusKm: 135,
            distanceAU: 0.009927017407098830,
            orbitPeriodDays: 21.36899463781863,
            orbitalInclination: 27.20902903280515 * D2R,
            ascendingNode: 168.3050139917620 * D2R,
            axialTilt: 0,
            massKg: 5.62e18,
            gravity: 0.0206,
            meanTempC: -180,
            moonCount: 0,
            description: {
              en: 'A spongy, porous outer moon tumbling chaotically through space — its rotation never settles into a fixed period.',
              fr: 'Une lune extérieure spongieuse et poreuse, qui bascule de façon chaotique dans l’espace — sa rotation ne se stabilise jamais sur une période fixe.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Hyperion_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Hyp%C3%A9rion_(lune)',
            },
          },
          cameraDistance: { educ: 0.6, explo: exploCameraDistance(135) },
          loadPriority: 23,
        },
      },
    },
    uranus: {
      kind: 'planet',
      radius: 2,
      rotationSpeed: _R(17.24),
      orbitalColor: 0x69d6d3,
      textureResolutions: { surface: ['2k', '1k'] },
      realData: {
        radiusKm: 25_559,
        distanceAU: 19.191,
        orbitPeriodDays: 30688.5,
        orbitalInclination: 0.773 * D2R,
        ascendingNode: 74.006 * D2R,
        axialTilt: 97.77 * D2R,
        massKg: 8.681e25,
        gravity: 8.69,
        meanTempC: -197,
        moonCount: 29, // 29ᵉ lune confirmée en 2023 (S/2023 U1) ; 28 était daté.
        description: {
          en: 'The ice giant tipped on its side, with an axis leaning at 98°, so it rolls along its orbit. Each season lasts 21 years.',
          fr: 'La géante de glace couchée sur le côté, avec un axe penché à 98°, si bien qu’elle roule le long de son orbite. Chaque saison dure 21 ans.',
        },
        wiki: {
          en: 'https://en.wikipedia.org/wiki/Uranus',
          fr: 'https://fr.wikipedia.org/wiki/Uranus_(plan%C3%A8te)',
        },
      },
      astroBody: Body.Uranus,
      cameraDistance: { educ: 10, explo: exploCameraDistance(25_559) },
      loadPriority: 9,
      satellites: {
        miranda: {
          kind: 'moon',
          displayName: { en: 'Miranda', fr: 'Miranda' },
          radius: 0.1,
          rotationSpeed: _R(1.414004013381316 * 24),
          orbitalColor: 0xb7b5ae,
          fallbackColor: 0xa8a6a0,
          frame: 'parentRelative',
          rotationBody: Body.Uranus,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          // JPL Horizons osculating elements, epoch 2000-01-01.5 TDB (EPHEM_TYPE=ELEMENTS,
          // TLIST=2451545.0), même méthode que les lunes de Saturne. L'inclinaison ~97° n'est
          // pas une orbite rétrograde : c'est l'écliptique qui est très inclinée par rapport
          // au plan équatorial d'Uranus (axe couché à 97,77°, voir realData.axialTilt
          // d'Uranus) — ces lunes orbitent normalement dans ce plan équatorial.
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.0008681390616993154,
            eccentricity: 0.0015098,
            inclinationRad: 97.25415391960598 * D2R,
            ascendingNodeRad: 172.0875833032825 * D2R,
            argPerihelionRad: 261.0221270814858 * D2R,
            meanAnomalyAtEpochRad: 62.06189119864032 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          // Aucune mosaïque globale contrôlée : Voyager 2 (survol unique, 1986) n'a imagé en
          // détail qu'environ la moitié de Miranda — vérifié en direct (2026-08-26, voir
          // texture-sources.json). Sphère de couleur unie plutôt qu'une texture inventée.
          textureResolutions: {},
          realData: {
            radiusKm: 235.8,
            distanceAU: 0.0008681390616993154,
            orbitPeriodDays: 1.414004013381316,
            orbitalInclination: 97.25415391960598 * D2R,
            ascendingNode: 172.0875833032825 * D2R,
            axialTilt: 0,
            massKg: 6.4e19,
            gravity: 0.0768,
            meanTempC: -213,
            moonCount: 0,
            description: {
              en: "Uranus's smallest major moon, a bizarre patchwork of giant fault canyons and terraced 'racetrack' features up to 20 km deep.",
              fr: 'La plus petite grande lune d’Uranus, un patchwork étrange de canyons de faille géants et de formations en terrasses profondes de jusqu’à 20 km.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Miranda_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Miranda_(lune)',
            },
          },
          cameraDistance: { educ: 0.7, explo: exploCameraDistance(235.8) },
          loadPriority: 24,
        },
        ariel: {
          kind: 'moon',
          displayName: { en: 'Ariel', fr: 'Ariel' },
          radius: 0.17,
          rotationSpeed: _R(2.520725632150754 * 24),
          orbitalColor: 0xc7c5bd,
          fallbackColor: 0xb9b8b2,
          frame: 'parentRelative',
          rotationBody: Body.Uranus,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.001276364069125674,
            eccentricity: 0.0015208,
            inclinationRad: 97.71931922807300 * D2R,
            ascendingNodeRad: 167.6455486422633 * D2R,
            argPerihelionRad: 45.35674156751863 * D2R,
            meanAnomalyAtEpochRad: 152.7943682479845 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: {},
          realData: {
            radiusKm: 578.9,
            distanceAU: 0.001276364069125674,
            orbitPeriodDays: 2.520725632150754,
            orbitalInclination: 97.71931922807300 * D2R,
            ascendingNode: 167.6455486422633 * D2R,
            axialTilt: 0,
            massKg: 1.251e21,
            gravity: 0.2492,
            meanTempC: -213,
            moonCount: 0,
            description: {
              en: "The brightest of Uranus's major moons, with the youngest surface and long canyons that may hold traces of past cryovolcanic flows.",
              fr: 'La plus brillante des grandes lunes d’Uranus, avec la surface la plus jeune et de longs canyons qui pourraient garder la trace d’anciens écoulements cryovolcaniques.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Ariel_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Ariel_(lune)',
            },
          },
          cameraDistance: { educ: 1, explo: exploCameraDistance(578.9) },
          loadPriority: 25,
        },
        umbriel: {
          kind: 'moon',
          displayName: { en: 'Umbriel', fr: 'Umbriel' },
          radius: 0.17,
          rotationSpeed: _R(4.145031502892753 * 24),
          orbitalColor: 0x716f6b,
          fallbackColor: 0x5c5a58,
          frame: 'parentRelative',
          rotationBody: Body.Uranus,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.001778181651275977,
            eccentricity: 0.0041702,
            inclinationRad: 97.66606723745439 * D2R,
            ascendingNodeRad: 167.6381821495947 * D2R,
            argPerihelionRad: 334.9516684490692 * D2R,
            meanAnomalyAtEpochRad: 271.2233789529364 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: {},
          realData: {
            radiusKm: 584.7,
            distanceAU: 0.001778181651275977,
            orbitPeriodDays: 4.145031502892753,
            orbitalInclination: 97.66606723745439 * D2R,
            ascendingNode: 167.6381821495947 * D2R,
            axialTilt: 0,
            massKg: 1.275e21,
            gravity: 0.2489,
            meanTempC: -213,
            moonCount: 0,
            description: {
              en: 'The darkest of the five major Uranian moons, heavily cratered with almost no sign of resurfacing since it formed.',
              fr: 'La plus sombre des cinq grandes lunes d’Uranus, fortement cratérisée et presque sans trace de resurfaçage depuis sa formation.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Umbriel_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Umbriel_(lune)',
            },
          },
          cameraDistance: { educ: 1, explo: exploCameraDistance(584.7) },
          loadPriority: 26,
        },
        titania: {
          kind: 'moon',
          displayName: { en: 'Titania', fr: 'Titania' },
          radius: 0.21,
          rotationSpeed: _R(8.706372907685905 * 24),
          orbitalColor: 0xaba89f,
          fallbackColor: 0x9a9893,
          frame: 'parentRelative',
          rotationBody: Body.Uranus,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.002916436400823477,
            eccentricity: 0.0024790,
            inclinationRad: 97.81836838381200 * D2R,
            ascendingNodeRad: 167.6178145945835 * D2R,
            argPerihelionRad: 202.1167721066045 * D2R,
            meanAnomalyAtEpochRad: 74.41677554285916 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: {},
          realData: {
            radiusKm: 788.4,
            distanceAU: 0.002916436400823477,
            orbitPeriodDays: 8.706372907685905,
            orbitalInclination: 97.81836838381200 * D2R,
            ascendingNode: 167.6178145945835 * D2R,
            axialTilt: 0,
            massKg: 3.4e21,
            gravity: 0.3651,
            meanTempC: -213,
            moonCount: 0,
            description: {
              en: "Uranus's largest moon, featuring one of the solar system's biggest known fault canyons, Messina Chasma.",
              fr: 'La plus grande lune d’Uranus, avec l’un des plus grands canyons de faille connus du système solaire, Messina Chasma.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Titania_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Titania_(lune)',
            },
          },
          cameraDistance: { educ: 1.2, explo: exploCameraDistance(788.4) },
          loadPriority: 27,
        },
        oberon: {
          kind: 'moon',
          displayName: { en: 'Oberon', fr: 'Obéron' },
          radius: 0.2,
          rotationSpeed: _R(13.46752377940373 * 24),
          orbitalColor: 0x9c9188,
          fallbackColor: 0x8f8681,
          frame: 'parentRelative',
          rotationBody: Body.Uranus,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.003900790441203894,
            eccentricity: 0.00055232,
            inclinationRad: 97.87585296035932 * D2R,
            ascendingNodeRad: 167.7555265636234 * D2R,
            argPerihelionRad: 254.0067252060520 * D2R,
            meanAnomalyAtEpochRad: 93.49629094330373 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: {},
          realData: {
            radiusKm: 761.4,
            distanceAU: 0.003900790441203894,
            orbitPeriodDays: 13.46752377940373,
            orbitalInclination: 97.87585296035932 * D2R,
            ascendingNode: 167.7555265636234 * D2R,
            axialTilt: 0,
            massKg: 3.076e21,
            gravity: 0.3542,
            meanTempC: -213,
            moonCount: 0,
            description: {
              en: "The outermost of Uranus's major moons, its heavily cratered, reddish surface scarred by one of the tallest known mountains in the solar system.",
              fr: 'La plus extérieure des grandes lunes d’Uranus, à la surface rougeâtre fortement cratérisée, marquée par l’une des plus hautes montagnes connues du système solaire.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Oberon_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Ob%C3%A9ron_(lune)',
            },
          },
          cameraDistance: { educ: 1.2, explo: exploCameraDistance(761.4) },
          loadPriority: 28,
        },
      },
    },

    neptune: {
      kind: 'planet',
      radius: 1.9,
      rotationSpeed: _R(16.11),
      orbitalColor: 0x647cff,
      textureResolutions: { surface: ['2k', '1k'] },
      realData: {
        radiusKm: 24_764,
        distanceAU: 30.069,
        orbitPeriodDays: 60182.0,
        orbitalInclination: 1.77 * D2R,
        ascendingNode: 131.784 * D2R,
        axialTilt: 28.32 * D2R,
        massKg: 1.024e26,
        gravity: 11.15,
        meanTempC: -201,
        moonCount: 16,
        description: {
          en: 'The most distant planet, invisible to the naked eye and found by calculation. Its winds reach 2,000 km/h, the fiercest in the Solar System.',
          fr: 'La planète la plus lointaine, invisible à l’œil nu et découverte par le calcul. Ses vents atteignent 2 000 km/h, les plus violents du Système solaire.',
        },
        wiki: {
          en: 'https://en.wikipedia.org/wiki/Neptune',
          fr: 'https://fr.wikipedia.org/wiki/Neptune_(plan%C3%A8te)',
        },
      },
      astroBody: Body.Neptune,
      cameraDistance: { educ: 10, explo: exploCameraDistance(24_764) },
      loadPriority: 10,
      satellites: {
        triton: {
          kind: 'moon',
          displayName: { en: 'Triton', fr: 'Triton' },
          radius: 0.28,
          rotationSpeed: -_R(141.047856),
          orbitalColor: 0x9dc4cf,
          fallbackColor: 0x7796a2,
          frame: 'parentRelative',
          rotationBody: Body.Neptune,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.00237169151,
            eccentricity: 0,
            inclinationRad: 157.3 * D2R,
            ascendingNodeRad: 178.1 * D2R,
            argPerihelionRad: 0,
            meanAnomalyAtEpochRad: 63 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          textureResolutions: { surface: ['8k', '4k', '2k', '1k'] },
          realData: {
            radiusKm: 1_352.6,
            distanceAU: 0.00237169151,
            orbitPeriodDays: 5.876994,
            orbitalInclination: 157.3 * D2R,
            ascendingNode: 178.1 * D2R,
            axialTilt: 0.4 * D2R,
            massKg: 2.14e22,
            gravity: 0.779,
            meanTempC: -235,
            moonCount: 0,
            description: {
              en: "Neptune's largest moon and the Solar System's only major retrograde satellite, with nitrogen geysers.",
              fr: "La plus grande lune de Neptune et la seule grande lune rétrograde du Système solaire, avec des geysers d'azote.",
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Triton_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Triton_(lune)',
            },
          },
          cameraDistance: { educ: 1.5, explo: exploCameraDistance(1_352.6) },
          loadPriority: 12,
        },
        proteus: {
          kind: 'moon',
          displayName: { en: 'Proteus', fr: 'Protée' },
          radius: 0.12,
          rotationSpeed: _R(1.122842386036011 * 24),
          orbitalColor: 0x6a6a6a,
          fallbackColor: 0x4a4a4a,
          frame: 'parentRelative',
          rotationBody: Body.Neptune,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          // JPL Horizons osculating elements, epoch 2000-01-01.5 TDB — cohérents avec la
          // période réelle publiée (1.122 j).
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.0007866074366734613,
            eccentricity: 0.0004949303539595451,
            inclinationRad: 28.99163681179519 * D2R,
            ascendingNodeRad: 48.27950205867285 * D2R,
            argPerihelionRad: 326.8036455837504 * D2R,
            meanAnomalyAtEpochRad: 283.6240862259231 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          // Aucune mosaïque photo globale contrôlée n'existe côté USGS pour Protée (une seule
          // face imagée par Voyager 2, jamais assemblée en carte globale contrôlée) — vérifié
          // en direct (2026-08-26). Sphère de couleur unie plutôt qu'une texture inventée.
          textureResolutions: {},
          realData: {
            radiusKm: 208,
            distanceAU: 0.0007866074366734613,
            orbitPeriodDays: 1.122842386036011,
            orbitalInclination: 28.99163681179519 * D2R,
            ascendingNode: 48.27950205867285 * D2R,
            axialTilt: 0,
            massKg: 3.871e19,
            gravity: 0.0597,
            meanTempC: -222,
            moonCount: 0,
            description: {
              en: "Neptune's second-largest moon, an irregularly shaped, tidally locked body near the size limit a body of its density can hold without becoming round.",
              fr: 'La deuxième plus grande lune de Neptune, un corps de forme irrégulière verrouillé par effet de marée, proche de la taille limite qu’un corps de sa densité peut atteindre sans devenir sphérique.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Proteus_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/Prot%C3%A9e_(lune)',
            },
          },
          cameraDistance: { educ: 1.2, explo: exploCameraDistance(208) },
          loadPriority: 13,
        },
        nereid: {
          kind: 'moon',
          displayName: { en: 'Nereid', fr: 'Néréide' },
          radius: 0.11,
          rotationSpeed: _R(11.594),
          orbitalColor: 0x8c8c8c,
          fallbackColor: 0x8c8c8c,
          frame: 'parentRelative',
          rotationBody: Body.Neptune,
          relativeEphemeris: { kind: 'horizonsParentRelative' },
          // JPL Horizons osculating elements, epoch 2000-01-01.5 TDB — cohérents avec la
          // période réelle publiée (~360.13 j). Rotation NON verrouillée : 11.594 h, mesure
          // bien déterminée par Kepler (2016) — sans lien avec sa période orbitale.
          relativeOrbitalElements: {
            semiMajorAxisAU: 0.03683979459947609,
            eccentricity: 0.7506509374056886,
            inclinationRad: 5.060553241702044 * D2R,
            ascendingNodeRad: 319.5912156886533 * D2R,
            argPerihelionRad: 297.0020523243177 * D2R,
            meanAnomalyAtEpochRad: 215.6255522626936 * D2R,
            epoch: new Date('2000-01-01T12:00:00Z'),
          },
          // Aucune mosaïque photo globale contrôlée n'existe côté USGS pour Néréide (résolution
          // Voyager 2 de ~43 km/pixel seulement — insuffisant pour une carte globale) — vérifié
          // en direct (2026-08-26). Sphère de couleur unie plutôt qu'une texture inventée.
          textureResolutions: {},
          realData: {
            radiusKm: 170,
            distanceAU: 0.03683979459947609,
            orbitPeriodDays: 359.879914569329,
            orbitalInclination: 5.060553241702044 * D2R,
            ascendingNode: 319.5912156886533 * D2R,
            axialTilt: 0,
            massKg: 3.1e19,
            gravity: 0.0716,
            meanTempC: -218,
            moonCount: 0,
            description: {
              en: 'A small, distant moon with the second-most eccentric orbit of any known moon, likely a captured object rather than one formed alongside Neptune.',
              fr: 'Une petite lune lointaine dotée de l’orbite la plus excentrique parmi les lunes connues après une autre, probablement un objet capturé plutôt que formé avec Neptune.',
            },
            wiki: {
              en: 'https://en.wikipedia.org/wiki/Nereid_(moon)',
              fr: 'https://fr.wikipedia.org/wiki/N%C3%A9r%C3%A9ide_(lune)',
            },
          },
          cameraDistance: { educ: 1.2, explo: exploCameraDistance(170) },
          loadPriority: 14,
        },
      },
    },

    // Petits corps (astéroïdes, comètes, planètes naines) — positionnés par éléments
    // orbitaux képlériens, définis dans `smallBodies.ts`. Fusionnés ici pour dériver comme
    // les autres corps (position instantanée, label Explo). Les corps disposant d'une
    // texture locale ont aussi un mesh et deviennent navigables dans les deux modes.
    ...SMALL_BODIES,
  },
};

// Dérive les chemins de texture depuis la clé du corps + les couches déclarées dans
// `textureResolutions` (nommage snake_case `{body}/{body}_{layer}`). Aucun chemin n'est
// écrit à la main dans le catalogue ci-dessus : c'est `catalog.texturePath` qui fait foi.
forEachBody(CELESTIAL_CONFIG, ({ name, config }) => {
  config.textures = deriveTextures(name, config);
  if (config.ring && !config.ring.textures) {
    config.ring.textures = ringTexturePath(name);
  }
});

// Fail-fast : un nom en doublon (corps ou satellite) écraserait silencieusement une entrée.
assertUniqueBodyNames(CELESTIAL_CONFIG);
// Fail-fast: a body without fallback, LOD or safe asset path must fail at startup.
assertValidCelestialCatalog(CELESTIAL_CONFIG);
