/**
 * `/sources` : d'où vient chaque donnée et chaque image que Galaxy livre, et sous quelle licence.
 *
 * Rien ici n'est une copie : chaque tableau est lu au build dans le fichier qui fait foi.
 *   - textures : `scripts/texture-sources.json` (bloc `imported`), croisé avec les couches que le
 *     catalogue livre réellement. Une couche SANS provenance fait échouer le build : une page qui
 *     la tairait mentirait par omission, et un contrôle qui l'ignorerait ne contrôlerait rien ;
 *   - modèles de forme : le `ModelConfig` du catalogue (crédit, carte de couleur, albédo) ;
 *   - éphémérides : `public/assets/ephemerides/manifest.json` ;
 *   - éléments orbitaux : `config/smallBodies.ts` et `config/interstellar.ts` ;
 *   - bibliothèques : `package.json` et le `package.json` de chaque dépendance installée ;
 *   - le texte juridique complet : `THIRD_PARTY_NOTICES.md`, rendu tel quel.
 *
 * Module PUR : données en entrée, pages en sortie.
 */
import type { CelestialConfig } from '@/types';
import { flattenBodies } from '@/config/catalog';
import { SMALL_BODY_ELEMENTS } from '@/config/smallBodies';
import { INTERSTELLAR_OBJECTS } from '@/config/interstellar';
import { escapeHtml } from './bodyLandingPage';
import {
  type Bilingual,
  type DocLocale,
  type DocPage,
  DOC_LOCALES,
  docPath,
  docSection,
  docTable,
} from './documentPage';
import { displayNameResolver, type EphemerisManifest } from './methodologyPage';
import { renderMarkdown } from './markdown';

export interface TextureProvenance {
  body: string;
  layer: string;
  license: string;
  credit: string;
  sourceUrl?: string;
  illustrative?: boolean;
}

export interface DependencyNotice {
  name: string;
  version: string;
  license: string;
  homepage: string | null;
}

export interface SourcesInput {
  config: CelestialConfig;
  textures: readonly TextureProvenance[];
  manifest: EphemerisManifest;
  dependencies: readonly DependencyNotice[];
  /** Contenu de `THIRD_PARTY_NOTICES.md`. */
  notices: string;
  /** `https://github.com/…/blob/main` : où pointent les liens relatifs du texte juridique. */
  repositoryBlobUrl: string;
  /** Date ISO affichée comme date des données (celle du build). */
  updated: string;
  origin: string;
}

/** Une couche de texture livrée par le catalogue : ce que la page doit sourcer. */
export interface ShippedTextureLayer {
  body: string;
  layer: string;
}

/**
 * Toutes les couches de texture que le catalogue charge réellement : chaque couche déclarée
 * dans `textureResolutions` avec au moins une résolution, plus l'anneau.
 */
export function shippedTextureLayers(
  config: CelestialConfig
): ShippedTextureLayer[] {
  const layers: ShippedTextureLayer[] = [];
  for (const [body, cfg] of flattenBodies(config)) {
    for (const [layer, resolutions] of Object.entries(
      cfg.textureResolutions ?? {}
    ))
      if (Array.isArray(resolutions) && resolutions.length > 0)
        layers.push({ body, layer });
    if (cfg.ring && cfg.ring.textureResolutions.length > 0)
      layers.push({ body, layer: 'ring' });
  }
  return layers;
}

/** Couches livrées sans entrée de provenance — doit être vide pour publier. */
export function missingTextureProvenance(
  config: CelestialConfig,
  textures: readonly TextureProvenance[]
): ShippedTextureLayer[] {
  const known = new Set(textures.map((t) => `${t.body}/${t.layer}`));
  return shippedTextureLayers(config).filter(
    (l) => !known.has(`${l.body}/${l.layer}`)
  );
}

const LICENSE_LABELS: Record<string, Bilingual> = {
  'public-domain': { en: 'Public domain', fr: 'Domaine public' },
  generated: {
    en: 'Generated by this project',
    fr: 'Générée par ce projet',
  },
};

const LAYER_LABELS: Record<string, Bilingual> = {
  surface: { en: 'surface', fr: 'surface' },
  clouds: { en: 'clouds', fr: 'nuages' },
  lights: { en: 'night lights', fr: 'lumières nocturnes' },
  normalMap: { en: 'relief (normal map)', fr: 'relief (normal map)' },
  spec: { en: 'land/ocean mask', fr: 'masque terre/mer' },
  ring: { en: 'ring', fr: 'anneau' },
};

const JD_UNIX_EPOCH = 2_440_587.5;
const isoFromJd = (jd: number): string =>
  new Date((jd - JD_UNIX_EPOCH) * 86_400_000).toISOString().slice(0, 10);

const link = (url: string, text: string): string =>
  `<a href="${escapeHtml(url)}" rel="noopener noreferrer">${text}</a>`;

export function sourcesPages(input: SourcesInput): DocPage[] {
  const missing = missingTextureProvenance(input.config, input.textures);
  if (missing.length > 0)
    throw new Error(
      `page /sources : couche(s) de texture livrée(s) sans provenance dans texture-sources.json : ${missing.map((m) => `${m.body}/${m.layer}`).join(', ')}`
    );
  if (input.dependencies.length === 0)
    throw new Error('page /sources : aucune dépendance lue dans package.json');
  return DOC_LOCALES.map((locale) => sourcesPage(input, locale));
}

function sourcesPage(input: SourcesInput, locale: DocLocale): DocPage {
  const { config, textures, manifest, dependencies, origin } = input;
  const L = (text: Bilingual): string => text[locale];
  const name = displayNameResolver(config);
  const flat = flattenBodies(config);
  const sections: string[] = [];

  sections.push(
    `      <section><p>${L({
      en: `Every table below is read at build time from the file that is authoritative for it, so this page cannot fall out of date with what the app actually ships. How positions are computed, and how accurate they are, is explained on the <a href="${docPath('methodology', locale)}">methodology page</a>.`,
      fr: `Chaque tableau ci-dessous est lu au build dans le fichier qui fait foi : cette page ne peut pas se désynchroniser de ce que l’application livre réellement. La façon dont les positions sont calculées, et leur précision, est expliquée sur la <a href="${docPath('methodology', locale)}">page de méthodologie</a>.`,
    })}</p></section>`
  );

  // ── Textures ──
  const shipped = new Set(
    shippedTextureLayers(config).map((l) => `${l.body}/${l.layer}`)
  );
  const textureRows = textures
    .filter((t) => shipped.has(`${t.body}/${t.layer}`))
    .sort(
      (a, b) =>
        name(a.body, locale).localeCompare(name(b.body, locale), locale) ||
        a.layer.localeCompare(b.layer)
    )
    .map((t) => [
      escapeHtml(name(t.body, locale)),
      escapeHtml(LAYER_LABELS[t.layer]?.[locale] ?? t.layer),
      escapeHtml(LICENSE_LABELS[t.license]?.[locale] ?? t.license),
      t.sourceUrl
        ? link(t.sourceUrl, escapeHtml(t.credit))
        : escapeHtml(t.credit),
      t.illustrative
        ? L({ en: 'illustrative', fr: 'illustrative' })
        : L({
            en: 'from real data',
            fr: 'issue de données réelles',
          }),
    ]);
  sections.push(
    docSection(
      'textures',
      L({ en: 'Surface textures', fr: 'Textures de surface' }),
      `<p>${L({
        en: 'An <strong>illustrative</strong> surface is not a scientific map: either no spacecraft has imaged the body well enough, or the images were never assembled into a global mosaic. Credits are quoted as recorded in the project’s provenance file.',
        fr: 'Une surface <strong>illustrative</strong> n’est pas une carte scientifique : soit aucune sonde n’a photographié le corps assez bien, soit les images n’ont jamais été assemblées en mosaïque globale. Les crédits sont cités tels qu’inscrits dans le fichier de provenance du projet.',
      })}</p>` +
        docTable(
          L({
            en: 'One row per texture layer the app loads',
            fr: 'Une ligne par couche de texture chargée par l’application',
          }),
          [
            L({ en: 'Body', fr: 'Corps' }),
            L({ en: 'Layer', fr: 'Couche' }),
            L({ en: 'Licence', fr: 'Licence' }),
            L({ en: 'Credit', fr: 'Crédit' }),
            L({ en: 'Nature', fr: 'Nature' }),
          ],
          textureRows
        )
    )
  );

  // ── Modèles de forme ──
  const modelRows = [...flat.entries()]
    .filter(([, cfg]) => cfg.model)
    .map(([body, cfg]) => {
      const model = cfg.model!;
      return [
        escapeHtml(name(body, locale)),
        escapeHtml(model.credit),
        escapeHtml(
          model.colourSource ??
            L({
              en: 'No global map published: uniform colour at the published albedo',
              fr: 'Aucune carte globale publiée : couleur uniforme à l’albédo publié',
            })
        ),
        `${model.albedo.toString().replace('.', locale === 'fr' ? ',' : '.')} (${escapeHtml(model.albedoSource)})`,
        escapeHtml(model.resolutions.join(', ')),
      ];
    });
  sections.push(
    docSection(
      'models',
      L({ en: '3D shape models', fr: 'Modèles de forme 3D' }),
      `<p>${L({
        en: 'Irregular bodies are drawn from their real mission shape models, reduced for the web without inventing geometry. Brightness is set by the published albedo; contrast and colour come from a mission map when one exists.',
        fr: 'Les corps irréguliers sont dessinés d’après leurs vrais modèles de forme de mission, allégés pour le web sans inventer de géométrie. La luminosité suit l’albédo publié ; contrastes et couleur viennent d’une carte de mission quand elle existe.',
      })}</p>` +
        docTable(
          L({ en: 'Shape models shipped', fr: 'Modèles de forme livrés' }),
          [
            L({ en: 'Body', fr: 'Corps' }),
            L({ en: 'Shape model', fr: 'Modèle de forme' }),
            L({ en: 'Colour source', fr: 'Source de la couleur' }),
            L({ en: 'Albedo (reference)', fr: 'Albédo (référence)' }),
            L({ en: 'Levels of detail', fr: 'Niveaux de détail' }),
          ],
          modelRows
        )
    )
  );

  // ── Éphémérides ──
  const ephemerisRows = Object.entries(manifest.bodies).map(([body, e]) => [
    escapeHtml(name(body, locale)),
    `<code>${escapeHtml(e.target)}</code>`,
    escapeHtml(
      e.center === 'sun'
        ? L({ en: 'Sun', fr: 'Soleil' })
        : name(e.center, locale)
    ),
    String(e.stepDays),
    `${isoFromJd(e.startJdTdb)} → ${isoFromJd(e.startJdTdb + (e.sampleCount - 1) * e.stepDays)}`,
  ]);
  sections.push(
    docSection(
      'ephemerides',
      L({ en: 'Ephemerides', fr: 'Éphémérides' }),
      `<p>${L({
        en: `Precomputed position files come from ${escapeHtml(manifest.source)} (state vectors, frame ${escapeHtml(manifest.frame)}), generated on ${escapeHtml(manifest.generatedAt.slice(0, 10))}. The Horizons target identifier is given so that anyone can request the same data. Planets, the Moon and the Galilean moons otherwise come from ${link('https://github.com/cosinekitty/astronomy', 'astronomy-engine')}; the optional small-body layer queries the ${link('https://ssd-api.jpl.nasa.gov/doc/sbdb_query.html', 'JPL Small-Body Database')} at runtime.`,
        fr: `Les fichiers de positions précalculées viennent de ${escapeHtml(manifest.source)} (vecteurs d’état, repère ${escapeHtml(manifest.frame)}), générés le ${escapeHtml(manifest.generatedAt.slice(0, 10))}. L’identifiant de cible Horizons est donné pour que chacun puisse demander les mêmes données. Planètes, Lune et lunes galiléennes viennent sinon d’${link('https://github.com/cosinekitty/astronomy', 'astronomy-engine')} ; la couche optionnelle des petits corps interroge la ${link('https://ssd-api.jpl.nasa.gov/doc/sbdb_query.html', 'JPL Small-Body Database')} à l’exécution.`,
      })}</p>` +
        docTable(
          L({ en: 'JPL Horizons files', fr: 'Fichiers JPL Horizons' }),
          [
            L({ en: 'Body', fr: 'Corps' }),
            L({ en: 'Horizons target', fr: 'Cible Horizons' }),
            L({ en: 'Centre', fr: 'Centre' }),
            L({ en: 'Step (days)', fr: 'Pas (jours)' }),
            L({ en: 'Coverage (TDB)', fr: 'Couverture (TDB)' }),
          ],
          ephemerisRows,
          3
        )
    )
  );

  // ── Éléments orbitaux ──
  const elementRows = [
    ...SMALL_BODY_ELEMENTS.map((el) => [
      escapeHtml(name(el.name, locale)),
      escapeHtml(el.epoch.slice(0, 10)),
      el.barycentric
        ? L({
            en: 'Solar System barycentre',
            fr: 'barycentre du Système solaire',
          })
        : L({ en: 'Sun', fr: 'Soleil' }),
    ]),
    ...INTERSTELLAR_OBJECTS.map((object) => [
      `${escapeHtml(name(object.name, locale))} (${escapeHtml(object.designation)})`,
      escapeHtml(object.elements.epoch.toISOString().slice(0, 10)),
      L({ en: 'Sun (hyperbolic orbit)', fr: 'Soleil (orbite hyperbolique)' }),
    ]),
  ];
  sections.push(
    docSection(
      'elements',
      L({ en: 'Orbital elements', fr: 'Éléments orbitaux' }),
      `<p>${L({
        en: 'Osculating elements taken from the live NASA/JPL Horizons API at the epoch shown, by the scripts in the repository; they are data values, not copied from a third-party compilation.',
        fr: 'Éléments osculateurs pris dans l’API NASA/JPL Horizons à l’époque indiquée, par les scripts du dépôt ; ce sont des valeurs de données, pas une copie d’une compilation tierce.',
      })}</p>` +
        docTable(
          L({ en: 'Keplerian element sets', fr: 'Jeux d’éléments képlériens' }),
          [
            L({ en: 'Body', fr: 'Corps' }),
            L({ en: 'Epoch', fr: 'Époque' }),
            L({ en: 'Centre', fr: 'Centre' }),
          ],
          elementRows
        )
    )
  );

  // ── Bibliothèques ──
  sections.push(
    docSection(
      'software',
      L({ en: 'Software', fr: 'Logiciels' }),
      docTable(
        L({
          en: 'Libraries bundled with the app',
          fr: 'Bibliothèques embarquées dans l’application',
        }),
        [
          L({ en: 'Library', fr: 'Bibliothèque' }),
          L({ en: 'Version', fr: 'Version' }),
          L({ en: 'Licence', fr: 'Licence' }),
        ],
        dependencies.map((d) => [
          d.homepage
            ? link(d.homepage, escapeHtml(d.name))
            : escapeHtml(d.name),
          escapeHtml(d.version),
          escapeHtml(d.license),
        ])
      )
    )
  );

  // ── Texte juridique complet ──
  sections.push(
    docSection(
      'notices',
      L({
        en: 'Third-party notices (full text)',
        fr: 'Mentions tierces (texte intégral, en anglais)',
      }),
      `<div class="doc-notices" lang="en">${renderMarkdown(
        // Le titre de premier niveau du fichier doublerait celui de la section.
        // `[^\n]*` et non `.*` : sous Windows le fichier arrive en CRLF, et `.` ne franchit pas
        // le `\r` — le titre restait alors en place, en double.
        input.notices.replace(/^#\s+[^\n]*\n/, ''),
        { repositoryBlobUrl: input.repositoryBlobUrl, headingShift: 1 }
      )}</div>`
    )
  );

  return {
    slug: 'sources',
    locale,
    canonical: `${origin}${docPath('sources', locale)}`,
    title: L({
      en: 'Sources and credits: data, images and licences',
      fr: 'Sources et crédits : données, images et licences',
    }),
    description: L({
      en: 'Where every texture, shape model, ephemeris and orbital element in Galaxy comes from, with its licence and credit, read from the project’s own provenance files.',
      fr: 'D’où vient chaque texture, modèle de forme, éphéméride et élément orbital de Galaxy, avec sa licence et son crédit, lus dans les fichiers de provenance du projet.',
    }),
    body: sections.join('\n'),
    updated: input.updated,
  };
}
